title: Oakland Pride
email: info@oaklandpride.org
description: Celebrating the LGBTQ+ community in Oakland, California. Oakland Pride 2026 is proudly produced by the Oakland LGBTQ Community Center.
baseurl: ""
url: "https://oaklandpride.org"
website: https://oaklandpride.org
twitter_username: oaklandpride
github_username: oaklandpride

permalink: /:categories/:year/:month/:day/:title/

pride-theme: "Coming Soon 2026"
eventdates: "September 2026 - Date TBA"
producer: "Oakland LGBTQ Community Center"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

sass:
  style: compressed


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
